sudo: required
services:
  - docker

before_install:
  - docker build -t chiragkalra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chiragkalra/react-test npm test

after_success:
  - docker build -t chiragkalra/multi-client ./client
  - docker build -t chiragkalra/multi-nginx ./nginx
  - docker build -t chiragkalra/multi-server ./server
  - docker build -t chiragkalra/multi-worker ./worker

  # Log In to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push To Docker Hub
  - docker push chiragkalra/multi-client
  - docker push chiragkalra/multi-nginx
  - docker push chiragkalra/multi-server
  - docker push chiragkalra/multi-worker
